# Generated by Django 4.2.2 on 2023-07-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='element',
            field=models.CharField(default='fire', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='star',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
