# Generated by Django 4.2.2 on 2023-07-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_states_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statedetails',
            name='armor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='armorSet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='atk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='boots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='bootsSet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='crd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='cri',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='defense',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='eff',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='helmet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='helmetSet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='necklace',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='necklaceSet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='res',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='ring',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='ringSet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='set1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='set2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='set3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='spd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='weapon',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='weaponSet',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
