# Generated by Django 4.2.2 on 2023-07-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_statedetails_armor_alter_statedetails_armorset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statedetails',
            name='armorSet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='bootsSet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='helmetSet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='necklaceSet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='ringSet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='set1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='set2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='set3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statedetails',
            name='weaponSet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='states',
            name='current_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_state', to='app.statedetails'),
        ),
        migrations.AlterField(
            model_name='states',
            name='editor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
