# Generated by Django 4.2.2 on 2023-07-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_statedetails_armorset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statedetails',
            old_name='armorSet',
            new_name='armor_set',
        ),
        migrations.RenameField(
            model_name='statedetails',
            old_name='bootsSet',
            new_name='boots_set',
        ),
        migrations.RenameField(
            model_name='statedetails',
            old_name='helmetSet',
            new_name='helmet_set',
        ),
        migrations.RenameField(
            model_name='statedetails',
            old_name='necklaceSet',
            new_name='necklace_set',
        ),
        migrations.RenameField(
            model_name='statedetails',
            old_name='ringSet',
            new_name='ring_set',
        ),
        migrations.RenameField(
            model_name='statedetails',
            old_name='weaponSet',
            new_name='weapon_set',
        ),
    ]
