# Generated by Django 4.2.2 on 2023-07-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_armorset_statedetails_armor_set_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characters',
            old_name='classes',
            new_name='role',
        ),
    ]
