# Generated by Django 4.2.2 on 2023-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_classes_characters_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='states',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
