# Generated by Django 4.2.2 on 2023-07-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_users_groups_users_is_superuser_users_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
    ]
