from django.db import models

class StateDetails(models.Model):
    atk = models.IntegerField(null=True)
    defense = models.IntegerField(null=True)
    health = models.IntegerField(null=True)
    spd = models.IntegerField(null=True)
    cri = models.IntegerField(null=True)
    crd = models.IntegerField(null=True)
    eff = models.IntegerField(null=True)
    res = models.IntegerField(null=True)
    weapon = models.IntegerField(null=True)
    helmet = models.IntegerField(null=True)
    armor = models.IntegerField(null=True)
    necklace = models.IntegerField(null=True)
    ring = models.IntegerField(null=True)
    boots = models.IntegerField(null=True)
    weaponSet = models.CharField(max_length=50, null=True, blank=True)
    helmetSet = models.CharField(max_length=50, null=True, blank=True)
    armorSet = models.CharField(max_length=50, null=True, blank=True)
    necklaceSet = models.CharField(max_length=50, null=True, blank=True)
    ringSet = models.CharField(max_length=50, null=True, blank=True)
    bootsSet = models.CharField(max_length=50, null=True, blank=True)
    set1 = models.CharField(max_length=50, null=True, blank=True)
    set2 = models.CharField(max_length=50, null=True, blank=True)
    set3 = models.CharField(max_length=50, null=True, blank=True)
