from django.db import models

class StateDetails(models.Model):
    atk = models.IntegerField()
    defense = models.IntegerField()
    health = models.IntegerField()
    spd = models.IntegerField()
    cri = models.IntegerField()
    crd = models.IntegerField()
    eff = models.IntegerField()
    res = models.IntegerField()
    weapon = models.IntegerField()
    helmet = models.IntegerField()
    armor = models.IntegerField()
    necklace = models.IntegerField()
    ring = models.IntegerField()
    boots = models.IntegerField()
    weaponSet = models.CharField(max_length=50)
    helmetSet = models.CharField(max_length=50)
    armorSet = models.CharField(max_length=50)
    necklaceSet = models.CharField(max_length=50)
    ringSet = models.CharField(max_length=50)
    bootsSet = models.CharField(max_length=50)
    set1 = models.CharField(max_length=50)
    set2 = models.CharField(max_length=50)
    set3 = models.CharField(max_length=50)
