from django.db import models

class StateDetails(models.Model):
    atk = models.IntegerField(null=True)
    defense = models.IntegerField(null=True)
    health = models.IntegerField(null=True)
    spd = models.IntegerField(null=True)
    cri = models.IntegerField(null=True)
    crd = models.IntegerField(null=True)
    eff = models.IntegerField(null=True)
    res = models.IntegerField(null=True)
    weapon = models.IntegerField(null=True)
    helmet = models.IntegerField(null=True)
    armor = models.IntegerField(null=True)
    necklace = models.IntegerField(null=True)
    ring = models.IntegerField(null=True)
    boots = models.IntegerField(null=True)
    weapon_set = models.CharField(max_length=50, blank=True)
    helmet_set = models.CharField(max_length=50, blank=True)
    armor_set = models.CharField(max_length=50, blank=True)
    necklace_set = models.CharField(max_length=50, blank=True)
    ring_set = models.CharField(max_length=50, blank=True)
    boots_set = models.CharField(max_length=50, blank=True)
    set1 = models.CharField(max_length=50, blank=True)
    set2 = models.CharField(max_length=50, blank=True)
    set3 = models.CharField(max_length=50, blank=True)
